CREATE DATABASE Pung;
USE Pung;

CREATE TABLE AllstarFull (playerid VARCHAR(255), yearID INT, gameNum INT, gameID VARCHAR(255), teamID VARCHAR(5), lgID VARCHAR(5), GP INT, startingPOS INT);
CREATE TABLE Appearances (yearID INT ,teamID VARCHAR (5) ,lgID VARCHAR(5) NULL,playerID VARCHAR(255),G_all INT,GS INT,G_batting INT,G_defense INT,G_p INT,G_c INT,G_1b INT,G_2b INT,G_3b INT,G_ss INT,G_lf INT,G_cf INT,G_rf INT,G_of INT,G_dh INT,G_ph INT,G_pr INT);
CREATE TABLE AwardsManagers (playerID VARCHAR(255) ,awardID VARCHAR(255) ,yearID INT ,lgID VARCHAR(5) ,tie VARCHAR(5) ,notes VARCHAR(255));
CREATE TABLE AwardsPlayers (playerID VARCHAR(255) ,awardID VARCHAR(255),yearID INT,lgID VARCHAR(5),tie VARCHAR(5),notes VARCHAR(255));
CREATE TABLE AwardsShareManagers(awardID VARCHAR(255),yearID INT ,lgID VARCHAR(5),playerID VARCHAR(255),poINTsWon INT,poINTsMax INT,votesFirst INT);
CREATE TABLE AwardsSharePlayers (awardID VARCHAR(255),yearID INT,lgID VARCHAR(5),playerID VARCHAR(255),poINTsWon INT,poINTsMax INT,votesFirst INT);
CREATE TABLE Batting (playerID VARCHAR(255),yearID INT,stINT INT,teamID VARCHAR(5),lgID INT,G INT,AB INT,R INT, H INT,2B INT ,3B INT,HR INT,RBI INT,SB INT,CS INT,BB INT,SO INT,IBB INT,HBP INT,SH INT,SF INT,GIDP INT);