CREATE DATABASE Pung;
USE Pung;

CREATE TABLE allstarfull (playerid VARCHAR(255), yearID INT, gameNum INT, gameID VARCHAR(255), teamID VARCHAR(5), lgID VARCHAR(5), GP INT, startingPOS INT);
CREATE TABLE appearances (yearID INT ,teamID VARCHAR (5) ,lgID VARCHAR(5) NULL,playerID VARCHAR(255),G_all INT,GS INT,G_batting INT,G_defense INT,G_p INT,G_c INT,G_1b INT,G_2b INT,G_3b INT,G_ss INT,G_lf INT,G_cf INT,G_rf INT,G_of INT,G_dh INT,G_ph INT,G_pr INT);
CREATE TABLE awardsmanagers (playerID VARCHAR(255) ,awardID VARCHAR(255) ,yearID INT ,lgID VARCHAR(5) ,tie VARCHAR(5) ,notes VARCHAR(255));
CREATE TABLE awardsplayers (playerID VARCHAR(255) ,awardID VARCHAR(255),yearID INT,lgID VARCHAR(5),tie VARCHAR(5),notes VARCHAR(255));
CREATE TABLE awardssharemanagers(awardID VARCHAR(255),yearID INT ,lgID VARCHAR(5),playerID VARCHAR(255),poINTsWon INT,poINTsMax INT,votesFirst INT);
CREATE TABLE awardsshareplayers (awardID VARCHAR(255),yearID INT,lgID VARCHAR(5),playerID VARCHAR(255),poINTsWon INT,poINTsMax INT,votesFirst INT);
CREATE TABLE batting (playerID VARCHAR(255),yearID INT,stINT INT,teamID VARCHAR(5),lgID INT,G INT,AB INT,R INT, H INT,2B INT ,3B INT,HR INT,RBI INT,SB INT,CS INT,BB INT,SO INT,IBB INT,HBP INT,SH INT,SF INT,GIDP INT);
CREATE TABLE battingpost (yearID INT,round VARCHAR(5),playerID VARCHAR(255),teamID VARCHAR(5),lgID VARCHAR(5),G INT,AB INT,R INT,H INT,2B INT,3B INT,HR INT,RBI INT,SB INT,CS INT,BB INT,SO INT,IBB INT,HBP INT,SH INT,SF INT ,GIDP INT);
CREATE TABLE collegeplaying (playerID VARCHAR(255),schoolID VARCHAR(255),yearID INT);
CREATE TABLE fielding (playerID VARCHAR(255),yearID INT,stint INT,teamID VARCHAR(5),lgID VARCHAR(5),POS VARCHAR(5),G INT,GS INT,InnOuts INT ,PO INT ,A INT,E INT,DP INT,PB INT,WP INT,SB INT,CS INT,ZR INT);
CREATE TABLE fieldingof (playerID VARCHAR(255),yearID INT,stint INT,Glf INT,Gcf INT,Grf INT);
CREATE TABLE fieldingofsplit (playerID VARCHAR(255),yearID INT,stint INT,teamID VARCHAR(5),lgID VARCHAR(5),POS VARCHAR(5),G INT,GS INT , InnOuts INT,PO INT,A INT,E INT,DP INT,PB INT,WP INT,SB INT,CS INT, ZR INT);
CREATE TABLE fieldingpost (playerID VARCHAR(255),yearID INT,teamID VARCHAR(5),lgID VARCHAR(5),round VARCHAR(5),POS VARCHAR(5),G INT,GS INT,InnOuts INT,PO INT,A INT,E INT,DP INT,TP INT,PB INT,SB INT,CS INT);
CREATE TABLE halloffame (playerID VARCHAR(255),yearID INT,votedBy VARCHAR(255),ballots INT,needed INT,votes INT,inducted VARCHAR (5),category VARCHAR(255),needed_note VARCHAR(255));
CREATE TABLE homegames (yearID INT, leagueID VARCHAR(5), teamID VARCHAR(5), parkKey VARCHAR(255), spanFirst DATE , spanLast DATE,games INT,openings INT,attendance INT); --note that I had to change the names
CREATE TABLE managers (playerID VARCHAR(255),yearID INT,teamID VARCHAR(5),lgID VARCHAR(5),inseason INT ,G INT, W INT,L INT,rank INT,plyrMgr VARCHAR(5));
CREATE TABLE managershalf (playerID VARCHAR(255),yearID INT,teamID VARCHAR(5),lgID VARCHAR(5),inseason INT,half INT,G INT,W INT,L INT,rank INT);
CREATE TABLE parks (parkKey VARCHAR(255),parkName VARCHAR(255),parkAlias VARCHAR(255),city VARCHAR(255),"state" VARCHAR(255) ,country VARCHAR(255)); --note that I had to change the names
CREATE TABLE people (playerID VARCHAR(255),birthYear INT,birthMonth INT,birthDay INT,birthCountry VARCHAR(255),birthState VARCHAR(255),birthCity VARCHAR(255),deathYear INT,deathMonth INT,deathDay INT,deathCountry VARCHAR(255),deathState VARCHAR(255),deathCity VARCHAR(255),nameFirst VARCHAR(255),nameLast VARCHAR(255),nameGiven VARCHAR(255), "weight" INT,height INT,bats VARCHAR(5),throws VARCHAR(5),debut DATE,finalGame DATE,retroID VARCHAR(255),bbrefID VARCHAR(255));
CREATE TABLE pitching (playerID VARCHAR(255),yearID INT,stint INT,teamID VARCHAR(5),lgID VARCHAR(5),W INT,L INT,G INT,GS INT,CG INT,SHO INT,SV INT,IPouts INT,H INT,ER INT ,HR INT ,BB INT ,SO INT,BAOpp FLOAT,ERA FLOAT,IBB INT,WP INT,HBP INT,BK INT,BFP INT,GF INT,R INT,SH INT,SF INT,GIDP INT);
CREATE TABLE pitchingpost (playerID VARCHAR(255),yearID INT,round VARCHAR(5),teamID VARCHAR(5),lgID VARCHAR(5),W INT,L INT,G INT,GS INT,CG INT,SHO INT,SV INT,IPouts INT,H INT,ER INT,HR INT,BB INT,SO INT,BAOpp FLOAT,ERA FLOAT,IBB INT,WP INT,HBP INT,BK INT,BFP INT,GF INT,R INT,SH INT,SF INT,GIDP INT);
CREATE TABLE salaries (yearID INT,teamID VARCHAR(5),lgID VARCHAR(5),playerID VARCHAR(255),salary INT);
CREATE TABLE schools(schoolID VARCHAR(255),name_full VARCHAR(255),city VARCHAR(255),"state" varchar(255),country VARCHAR(255));
CREATE TABLE seriespost(yearID INT,round VARCHAR(5),teamIDwinner VARCHAR(5),lgIDwinner VARCHAR(5),teamIDloser VARCHAR(5),lgIDloser VARCHAR(5),wins INT,losses INT,ties INT);
CREATE TABLE teams (yearID INT ,lgID VARCHAR(5),teamID VARCHAR(5),franchID VARCHAR(5),divID VARCHAR(5),Rank INT,G INT,Ghome INT,W INT,L INT,DivWin VARCHAR(5),WCWin VARCHAR(5),LgWin VARCHAR(5),WSWin VARCHAR(5),R INT,AB INT,H INT,2B INT,3B INT,HR INT,BB INT,SO INT,SB INT,CS INT,HBP INT,SF INT,RA INT,ER INT,ERA FLOAT,CG INT,SHO INT,SV INT,IPouts INT,HA INT,HRA INT,BBA INT,SOA INT,E INT,DP INT,FP FLOAT, "name" VARCHAR(255),park VARCHAR(255),attendance INT,BPF INT,PPF INT,teamIDBR VARCHAR(5),teamIDlahman45 VARCHAR(5),teamIDretro VARCHAR(5));
CREATE TABLE teamsfranchises (franchID VARCHAR(5),franchName VARCHAR(255),active VARCHAR(5),NAassoc VARCHAR(5));
CREATE TABLE teamshalf (yearID INT,lgID VARCHAR(5),teamID VARCHAR(5),Half INT,divID VARCHAR(5),DivWin VARCHAR(5),Rank INT,G INT,W INT,L INT);
